name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rylabs/devcontainer-ruby
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/setup-buildx-action@v1
        id: ruby2_6_3
      -
        name: Ruby 2.6.3
        run: echo ${{ steps.ruby2_6_3.outputs.name }}
      -
        name: Build against Ruby 2.6.3
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.ruby2_6_3.outputs.name }}
          context: .
          build-args: |
            RUBY_VERSION=2.6.3
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: 2.6.3
