name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        id: ruby2_6_6
      -
        uses: docker/setup-buildx-action@v1
        id: ruby2_7_3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build against Ruby 2.6.6
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.ruby2_6_6.outputs.name }}
          context: .
          build-args: |
            RUBY_VERSION=2.6.6
          push: ${{ github.event_name != 'pull_request' }}
          tags: rylabs/ruby-devcontainer:2.6.6
      -
        name: Build against Ruby 2.7.3
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.ruby2_7_3.outputs.name }}
          context: .
          build-args: |
            RUBY_VERSION=2.7.3
          push: ${{ github.event_name != 'pull_request' }}
          tags: rylabs/ruby-devcontainer:2.7.3
